In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<h1>Loading Dataset</h1>

In [2]:
dataset = pd.read_csv("Datasets\\flipcart\\flipkart_mobile.csv")

In [3]:
dataset

,Brand,Model,Color,Memory,Storage,Rating,Selling Price,Original Price
0,OPPO,A53,Moonlight Black,4 GB,64 GB,4.5,11990.0,15990.0
1,OPPO,A53,Mint Cream,4 GB,64 GB,4.5,11990.0,15990.0
2,OPPO,A53,Moonlight Black,6 GB,128 GB,4.3,13990.0,17990.0
3,OPPO,A53,Mint Cream,6 GB,128 GB,4.3,13990.0,17990.0
4,OPPO,A53,Electric Black,4 GB,64 GB,4.5,11990.0,15990.0
...,...,...,...,...,...,...,...,...
2642,Xiaomi,Redmi Y3,Bold Red,4 GB,64 GB,4.3,12999.0,13999.0
2643,Xiaomi,Redmi Y3,Elegant Blue,3 GB,32 GB,4.3,9450.0,NaN
2644,Xiaomi,Redmi Y3,Elegant Blue,4 GB,64 GB,4.2,12999.0,NaN
2645,Xiaomi,Redmi Y3,Prime Black,3 GB,32 GB,4.2,9950.0,NaN
2646,Xiaomi,Redmi Y3,Prime Black,4 GB,64 GB,4.3,12499.0,13999.0

<h1>Cleaning Dataset(Removing unwanted Space)</h1>

In [4]:
dataset.columns()

TypeError: 'Index' object is not callable